### ISSUE TITLE
Converting Bip32 HD wallet into a cosmos account

### ISSUE THREAD

**Issue by chtmorris** [chtmorris/Vanity-Wallets#1]
I’m trying to figure out how to convert a Bip32 HD wallet into a cosmos account.

Relevant files in the cosmos-sdk are:

- HD Path Derivation:  https://github.com/cosmos/cosmos-sdk/blob/master/crypto/keys/hd/hdpath.go

- And then creating address:  https://github.com/cosmos/cosmos-sdk/blob/master/crypto/keys/keybase.go

My aim is to only extract the code that I need for the conversion. My problem is that these files reference all sorts of things and it’s a little overwhelming.

This seems to be a js implementation - https://github.com/okwme/js-cosmos-wallet/blob/master/src/js-cosmos-wallet.ts. Line 45 seems to be what I’m looking for (bechify) but in js and not go.

**Comment by shazow** [comment]
The way BIP32 HD wallets work is you have a "Master" key, and then you derive a tree of child keys and addresses from it.

To compare, the way you're doing the Ethereum thing is you're generating a random private key, producing a public key from it, converting it into an address, then discarding if it doesn't fit.

With BIP32, there's two ways to get a variety of addresses:
1. You can do a similar approach: loop { generate random private key, [produce an HD wallet structure from it](https://godoc.org/github.com/cosmos/cosmos-sdk/crypto/keys#NewMultiInfo), take a fixed path for a child, check the address of that child, discard if it doesn't fit }
2. Or you can do something kinda neater, where you take any private key as an input (so you can use your existing master key if you want), then do: loop { given an existing HD wallet structure from the input key, take a random sub-path for a child, check the address for that child, discard if it doesn't fit }

First option will be more similar to your ethereum code, but #2 will take advantage of BIP32. (Btw Ethereum also supports BIP32, but I'm not sure where the helpers are for that, certainly not in geth).

Does that make sense?

**Comment by chtmorris** [comment]
@shazow this makes a lot of sense, and I like option 2 a lot!

However, that doesn't actually solve my current issue. What I am trying to figure out is how to convert a BIP32 address into a cosmos address that starts "cosmos3iedjxxxxx...."

The [js implementation](https://github.com/okwme/js-cosmos-wallet/blob/master/src/js-cosmos-wallet.ts) uses `bech32.encode(prefix, words)`. So I think I need something similar in go

**Comment by shazow** [comment]
I think you want: https://godoc.org/github.com/cosmos/cosmos-sdk/types#Bech32ifyAccPub

**Comment by shazow** [comment]
Eg:
https://github.com/cosmos/cosmos-sdk/blob/master/crypto/keys/keybase_test.go#L65-L67
https://github.com/cosmos/cosmos-sdk/blob/master/crypto/keys/types_test.go#L28

**Comment by chtmorris** [comment]
Working now, but painfully slow. Using the cosmos sdk to create the mnemonic and keys.

I think a faster option might be to use option 1 from @shazow above. My only fear is that existing wallets (e.g. Lunie with Ledger integration) do not seem to give the option to take a random sub path from an HD wallet. So it would be a pretty bad user experience.
